name: Shawn Lestage
favicon: null
layout_spectrum: 0.004754743771627545
typography_spectrum: 0.9927738523110747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8388205990195274
  lightness: 0.7816261686384678
  saturation: 0.7068947723601013
  rhythmicContrast: 0.29054702422581613
purpose: []
